PRODUCT_CATALOG = [
    {
        "key": "iphone-15",
        "aliases": ["iphone-15", "iphone15", "apple-iphone-15", "apple iphone 15"],
        "category": "phones",
        "brand": "Apple",
        "name": "iPhone 15",
        "price": 799,
        "rating": 4.7,
        "review_count": 18420,
        "quality_base": 8.9,
        "pros": ["Excellent cameras", "Strong long-term software support", "Premium build quality"],
        "cons": ["Expensive for 128GB", "Limited customization", "Charging speed trails some rivals"],
        "summary": "A polished premium phone with reliable cameras, smooth performance, and strong long-term value.",
        "specs": ["48MP camera", "A16 chip", "128GB", "6.1-inch OLED", "USB-C"],
    },
    {
        "key": "galaxy-s24",
        "aliases": ["galaxy-s24", "galaxys24", "samsung-galaxy-s24", "samsung galaxy s24"],
        "category": "phones",
        "brand": "Samsung",
        "name": "Galaxy S24",
        "price": 749,
        "rating": 4.6,
        "review_count": 13780,
        "quality_base": 8.8,
        "pros": ["Great display", "Versatile cameras", "Strong AI features and customization"],
        "cons": ["Battery is good, not class-leading", "Compact size may not suit everyone", "Some features feel Samsung-specific"],
        "summary": "An all-round flagship with a vivid display, flexible software, and a slightly lower price than the top iPhone.",
        "specs": ["50MP camera", "Snapdragon/Exynos", "128GB", "6.2-inch AMOLED", "120Hz"],
    },
    {
        "key": "pixel-8",
        "aliases": ["pixel-8", "pixel8", "google-pixel-8", "google pixel 8"],
        "category": "phones",
        "brand": "Google",
        "name": "Pixel 8",
        "price": 699,
        "rating": 4.5,
        "review_count": 10140,
        "quality_base": 8.5,
        "pros": ["Excellent photo processing", "Clean Android experience", "Good value at its price"],
        "cons": ["Charging is still modest", "Gaming performance is not the strongest", "Battery is solid, not standout"],
        "summary": "A camera-first Android phone that offers a clean software experience and good value for mainstream buyers.",
        "specs": ["50MP camera", "Tensor G3", "128GB", "6.2-inch OLED", "7 years updates"],
    },
    {
        "key": "sony-wh-1000xm5",
        "aliases": ["sony-wh-1000xm5", "wh1000xm5", "sony wh-1000xm5", "sony xm5"],
        "category": "headphones",
        "brand": "Sony",
        "name": "WH-1000XM5",
        "price": 349,
        "rating": 4.8,
        "review_count": 15410,
        "quality_base": 9.2,
        "pros": ["Best-in-class noise cancellation", "Warm, detailed sound", "Excellent comfort for long sessions"],
        "cons": ["Does not fold inward", "Premium price", "Touch controls need some adjustment"],
        "summary": "A top-tier wireless headphone with elite ANC and a very safe premium recommendation.",
        "specs": ["30-hour battery", "ANC", "Multipoint", "LDAC", "Fast charge"],
    },
    {
        "key": "bose-qc-ultra",
        "aliases": ["bose-qc-ultra", "qc-ultra", "bose qc ultra", "bose quietcomfort ultra"],
        "category": "headphones",
        "brand": "Bose",
        "name": "QuietComfort Ultra",
        "price": 379,
        "rating": 4.7,
        "review_count": 9220,
        "quality_base": 9.0,
        "pros": ["Superb comfort", "Excellent ANC", "Immersive audio mode is enjoyable"],
        "cons": ["Usually pricier than Sony", "Battery life is only average for the class", "App experience is not the cleanest"],
        "summary": "A comfort-first premium headphone with great ANC and a refined, travel-friendly feel.",
        "specs": ["24-hour battery", "ANC", "Spatial audio", "Multipoint", "Premium comfort"],
    },
    {
        "key": "soundcore-q45",
        "aliases": ["soundcore-q45", "q45", "anker soundcore q45", "soundcore space q45"],
        "category": "headphones",
        "brand": "Soundcore",
        "name": "Space Q45",
        "price": 149,
        "rating": 4.4,
        "review_count": 11860,
        "quality_base": 7.9,
        "pros": ["Excellent value", "Long battery life", "Good ANC for the price"],
        "cons": ["Sound is less refined than premium rivals", "Build feels less premium", "Microphone performance is average"],
        "summary": "A smart buy for budget-conscious shoppers who still want solid ANC and battery life.",
        "specs": ["50-hour battery", "ANC", "App EQ", "Hi-Res Audio", "Budget pick"],
    },
    {
        "key": "macbook-air-m3",
        "aliases": ["macbook-air-m3", "macbook air m3", "apple macbook air m3"],
        "category": "laptops",
        "brand": "Apple",
        "name": "MacBook Air M3",
        "price": 1099,
        "rating": 4.9,
        "review_count": 7860,
        "quality_base": 9.4,
        "pros": ["Excellent efficiency and battery life", "Premium build", "Very strong everyday performance"],
        "cons": ["Port selection is limited", "Upgrades get expensive fast", "Gaming remains limited"],
        "summary": "A polished thin-and-light laptop with superb battery life and one of the best mainstream user experiences.",
        "specs": ["M3 chip", "13.6-inch display", "8GB RAM", "256GB SSD", "18-hour battery"],
    },
    {
        "key": "dell-xps-13",
        "aliases": ["dell-xps-13", "xps-13", "dell xps 13"],
        "category": "laptops",
        "brand": "Dell",
        "name": "XPS 13",
        "price": 999,
        "rating": 4.5,
        "review_count": 6340,
        "quality_base": 8.6,
        "pros": ["Compact premium design", "Sharp display", "Strong portability"],
        "cons": ["Can run warm under load", "Port selection is limited", "Value depends heavily on sale price"],
        "summary": "A stylish ultrabook for buyers who want portability and a premium Windows feel.",
        "specs": ["Intel Core Ultra", "13.4-inch display", "16GB RAM", "512GB SSD", "Lightweight"],
    },
    {
        "key": "asus-zenbook-14",
        "aliases": ["asus-zenbook-14", "zenbook-14", "asus zenbook 14"],
        "category": "laptops",
        "brand": "Asus",
        "name": "Zenbook 14 OLED",
        "price": 899,
        "rating": 4.6,
        "review_count": 5920,
        "quality_base": 8.8,
        "pros": ["Great OLED screen", "Strong specs for the price", "Better value than many premium rivals"],
        "cons": ["Speakers are fine, not standout", "Battery can vary by workload", "Design is less iconic than XPS or MacBook"],
        "summary": "A value-driven premium laptop with a great display and strong hardware for the money.",
        "specs": ["Ryzen/Core Ultra", "14-inch OLED", "16GB RAM", "512GB SSD", "Value favorite"],
    },
    {
        "key": "brand-a-protein-oats",
        "aliases": ["brand-a-protein-oats", "brand a protein oats", "brand a oats"],
        "category": "protein-oats",
        "brand": "Brand A",
        "name": "Brand A Protein Oats",
        "price": 3.99,
        "rating": 4.2,
        "review_count": 320,
        "quality_base": 7.5,
        "pros": ["Good protein content", "Tasty flavors", "Convenient single-serve packets"],
        "cons": ["Higher price than regular oats", "Some flavors are too sweet", "Texture can be a bit clumpy"],
        "summary": "A solid choice for those looking to boost their breakfast with extra protein, though it comes at a premium.",
        "specs": ["10g protein per serving", "Variety of flavors", "Single-serve packets"],
    },
    {
        "key": "brand-b-protein-oats",
        "aliases": ["brand-b-protein-oats", "brand b protein oats", "brand b oats"],
        "category": "protein-oats",
        "brand": "Brand B",
        "name": "Brand B Protein Oats",
        "price": 4.49,
        "rating": 4.5,
        "review_count": 450,
        "quality_base": 7.8,
        "pros": ["High protein content", "Good texture", "Less sweet than some competitors"],
        "cons": ["Pricey compared to regular oats", "Limited flavor options", "Some find the taste bland"],
        "summary": "A higher-protein option for oat lovers who want a less sweet, more textured breakfast boost.",
        "specs": ["15g protein per serving", "Less sweet", "Good texture"],
    },
    {
        "key": "brand-c-protein-oats",
        "aliases": ["brand-c-protein-oats", "brand c protein oats", "brand c oats"],
        "category": "protein-oats",
        "brand": "Brand C",
        "name": "Brand C Protein Oats",
        "price": 3.49,
        "rating": 4.0,
        "review_count": 210,
        "quality_base": 7.2,
        "pros": ["Affordable price", "Decent protein content", "Good for mixing with other ingredients"],
        "cons": ["Lower protein than some competitors", "Texture can be inconsistent", "Flavor is basic"],
        "summary": "A budget-friendly protein oat option that works well as a base for adding your own flavors and mix-ins.",
        "specs": ["8g protein per serving", "Affordable", "Good mix-in base"],
    },
]

SAMPLE_SETS = {
    "phones": [
        "https://shop.example.com/apple-iphone-15",
        "https://shop.example.com/samsung-galaxy-s24",
        "https://shop.example.com/google-pixel-8",
    ],
    "headphones": [
        "https://shop.example.com/sony-wh-1000xm5",
        "https://shop.example.com/bose-qc-ultra",
        "https://shop.example.com/soundcore-q45",
    ],
    "laptops": [
        "https://shop.example.com/macbook-air-m3",
        "https://shop.example.com/dell-xps-13",
        "https://shop.example.com/asus-zenbook-14",
    ],
    "protein-oats": [
        "https://shop.example.com/brand-a-protein-oats",
        "https://shop.example.com/brand-b-protein-oats",
        "https://shop.example.com/brand-c-protein-oats",
    ],
}
